const translations = {
    vi: {
        page_title: "Giới thiệu bản thân",
        information: "Giới thiệu",
        aims: "Mục tiêu",
        studies: "Học vấn",
        skills: "Kỹ năng",
        projects: "Dự án",
        hobbies: "Sở thích",
        contact: "Liên hệ",

        name: "Nguyễn Thanh Sơn",
        title: "Sinh viên IT",
        dob_label: "Ngày sinh: ",
        gender_label: "Giới tính: ",
        phone_label: "Điện thoại: ",
        email_label: "Email: ",
        address_label: "Địa chỉ: ",
        dob: "19/08/2003",
        gender: "Nam",
        phone: "+84 826 624 629",
        email: "thanhsonnguyen1908@gmail.com",
        address: "62C/13, Bà Hom, Phường 13, Quận 6, TP.HCM",

        aims_title: "MỤC TIÊU NGHỀ NGHIỆP",
        aims_description: "Là sinh viên năm 3 chuyên ngành Công nghệ Thông tin, tôi mong muốn áp dụng kiến thức và kỹ năng đã học vào thực tiễn thông qua các cơ hội thực tập và làm việc tại một công ty công nghệ. Mục tiêu của tôi là phát triển sự nghiệp trong lĩnh vực phát triển phần mềm, nơi tôi có thể đóng góp vào các dự án sáng tạo và học hỏi từ những chuyên gia trong ngành.",
        
        studies_title: "HỌC VẤN",
        studies_duration: "08/2021 _ 08/2025",
        studies_institute: "Đại học Khoa học Tự nhiên TP.HCM",
        studies_status: "Sinh viên năm 3",
        studies_gpa: "GPA: 3.22/4.0",

        skills_title: "KỸ NĂNG",
        skill_python: "Python",
        skill_python_level: "Mới bắt đầu",
        skill_c: "C/C++",
        skill_c_level: "Mới bắt đầu",
        skill_wpf: ".NET/C# (WPF)",
        skill_wpf_level: "Cơ bản",
        skill_asp: ".NET/C# (ASP.NET)",
        skill_asp_level: "Mới bắt đầu",
        skill_jsp: "Java Spring Boot",
        skill_jsp_level: "Mới bắt đầu",
        skill_toeic: "TOEIC",
        skill_toeic_listening: "Nghe: 310",
        skill_toeic_reading: "Đọc: 310",

        projects_title: "DỰ ÁN",
        laboratory_application_project_name_1: "Laboratory Application",
        laboratory_application_project_link: "Github",
        laboratory_application_project_description_1: "Là ứng dụng học tập được phát triển bằng C#/.NET, hỗ trợ nhiều môn học. Được xây dựng dựa trên một cá nhân với mục đích học hỏi công nghệ mới.",
        project_2_name_1: "Planora",
        project_2_link: "Github",
        project_2_description_1: "Là dự án phát triển ứng dụng web quản lý tiến độ phát triển phần mềm có tích hợp AI.",
        project_2_description_2: "Trách nhiệm trong dự án:",
        project_2_description_1_item_1: "Xử lý prompt AI chuyển thành Tasks cho người dùng.",
        project_2_description_1_item_2: "Hoàn thiện chức năng chart.",
        project_3_name_1: "MessApp",
        project_3_link: "Github",
        project_3_description: "Là ứng dụng nhắn tin được phát triển bằng C#/.NET, hỗ trợ giao tiếp theo thời gian thực. Được xây dựng là một dự án cá nhân để tìm hiểu công nghệ mới.",
        project_4_name_1: "OctaTunes",
        project_4_link: "Github",
        project_4_description_1: "Là ứng dụng phát nhạc trực tuyến trên nền tảng Android tương tự Spotify. Được thiết kế và hoàn thiện với nhóm có 5 thành viên.",
        project_4_description_2: "Trách nhiệm trong dự án:", // Key này bị thiếu
        project_4_description_2_item_1: "Xây dựng giao diện, xử lý logic cho phân hệ Admin.",

        hobbies_title: "SỞ THÍCH",
        hobby_music: "Nghe nhạc, xem phim",
        hobby_games: "Chơi game",
        hobby_coding: "Viết code",
        hobby_research: "Nghiên cứu công nghệ",

        contact_title: "LIÊN HỆ",
        contact_website: "Website cá nhân",
        contact_facebook: "Facebook",
        contact_email: "Email",
        contact_github: "Github"
    },
    en: {
        page_title: "Biography",
        information: "Information",
        aims: "Aims",
        studies: "Studies",
        skills: "Skills",
        projects: "Projects",
        hobbies: "Hobbies",
        contact: "Contact",

        name: "Nguyen Thanh Son",
        title: "IT Student",
        dob_label: "Date of Birth: ",
        gender_label: "Gender: ",
        phone_label: "Phone: ",
        email_label: "Email: ",
        address_label: "Address: ",
        dob: "19/08/2003",
        gender: "Male",
        phone: "+84 826 624 629",
        email: "thanhsonnguyen1908@gmail.com",
        address: "62C/13, Ba Hom, Ward 13, District 6, HCM City",

        aims_title: "CAREER OBJECTIVES",
        aims_description: "As a third-year Information Technology major, I am eager to apply my knowledge and skills in a practical setting through internships and job opportunities at a tech company. My goal is to develop a career in software development, where I can contribute to innovative projects and learn from industry experts.",
        studies_title: "EDUCATION",
        studies_duration: "08/2021 _ 08/2025",
        studies_institute: "University of Science, HCM City",
        studies_status: "3rd year student",
        studies_gpa: "GPA: 3.22/4.0",

        skills_title: "SKILLS",
        skill_python: "Python",
        skill_python_level: "Beginner",
        skill_c: "C/C++",
        skill_c_level: "Beginner",
        skill_wpf: ".NET/C# (WPF)",
        skill_wpf_level: "Basic",
        skill_asp: ".NET/C# (ASP.NET)",
        skill_asp_level: "Beginner",
        skill_jsp: "Java Spring Boot",
        skill_jsp_level: "Beginner",
        skill_toeic: "TOEIC",
        skill_toeic_listening: "Listening: 310",
        skill_toeic_reading: "Reading: 310",

        projects_title: "PROJECTS",
        laboratory_application_project_name_1: "Laboratory Application",
        laboratory_application_project_link: "Github",
        laboratory_application_project_description_1: "A learning application developed with C#/.NET, supporting multiple subjects. Built as a personal project to learn new technology.",
        project_2_name_1: "Planora",
        project_2_link: "Github",
        project_2_description_1: "A web application project for managing software development progress, integrated with AI.",
        project_2_description_2: "Responsibilities in the project:",
        project_2_description_1_item_1: "Processing AI prompts into tasks for users.",
        project_2_description_1_item_2: "Completing the chart functionality.",
        project_3_name_1: "MessApp",
        project_3_link: "Github",
        project_3_description: "A messaging application developed with C#/.NET, supporting real-time communication. Built as a personal project to learn new technology.",
        project_4_name_1: "OctaTunes",
        project_4_link: "Github",
        project_4_description_1: "An online music streaming application on the Android platform, similar to Spotify. Designed and completed with a team of 5 members.",
        project_4_description_2: "Responsibilities in the project:",
        project_4_description_2_item_1: "Built the UI and handled logic for the Admin subsystem.",

        hobbies_title: "HOBBIES",
        hobby_music: "Listening to music, watching movies",
        hobby_games: "Playing games",
        hobby_coding: "Coding",
        hobby_research: "Researching technology",

        contact_title: "CONTACT",
        contact_website: "Personal website",
        contact_facebook: "Facebook",
        contact_email: "Email",
        contact_github: "Github"
    }
};

function changeLanguage(lang) {
    document.documentElement.lang = lang;

    document.querySelectorAll('[data_key]').forEach(element => {
        const key = element.getAttribute('data_key');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
}
