const translations = {
    vi: {
        page_title: "Giới thiệu bản thân",
        information: "Giới thiệu",
        aims: "Mục tiêu",
        studies: "Học vấn",
        skills: "Kỹ năng",
        hobbies: "Sở thích",
        contact: "Liên hệ",
        name: "Nguyễn Thanh Sơn",
        title: "Sinh viên IT",
        dob_label: "Ngày sinh: ",
        gender_label: "Giới tính: ",
        phone_label: "Điện thoại: ",
        email_label: "Email: ",
        address_label: "Địa chỉ: ",
        dob: "19/08/2003",
        gender: "Nam",
        phone: "+84 826 624 629",
        email: "thanhsonnguyen1908@gmail.com",
        address: "62C/13, Bà Hom, Phường 13, Quận 6, TP.HCM",
        aims_title: "MỤC TIÊU NGHỀ NGHIỆP",
        aims_description: "Là sinh viên năm 3 chuyên ngành Công nghệ Thông tin, tôi mong muốn áp dụng kiến thức và kỹ năng đã học vào thực tiễn thông qua các cơ hội thực tập và làm việc tại một công ty công nghệ. Mục tiêu của tôi là phát triển sự nghiệp trong lĩnh vực phát triển phần mềm, nơi tôi có thể đóng góp vào các dự án sáng tạo và học hỏi từ những chuyên gia trong ngành.",
        studies_title: "HỌC VẤN",
        studies_duration: "08/2021 _ 08/2025",
        studies_institute: "Đại học Khoa học Tự nhiên TP.HCM",
        studies_status: "Sinh viên năm 3",
        studies_gpa: "GPA: 3.12/4.0",
        skills_title: "KỸ NĂNG",
        skill_python: "Python",
        skill_python_level: "Basic",
        skill_c: "C/C++",
        skill_c_level: "Basic",
        skill_dotnet: ".NET/C#",
        skill_dotnet_level: "Basic",
        hobbies_title: "SỞ THÍCH",
        hobby_music: "Nghe nhạc, xem phim",
        hobby_games: "Chơi game",
        hobby_coding: "Viết code",
        hobby_research: "Nghiên cứu công nghệ",
        contact_title: "LIÊN HỆ",
        contact_website: "Website cá nhân",
        contact_facebook: "Facebook",
        contact_email: "Email",
        contact_github: "Github"
    },
    en: {
        page_title: "Biography",
        information: "Information",
        aims: "Aims",
        studies: "Studies",
        skills: "Skills",
        hobbies: "Hobbies",
        contact: "Contact",
        name: "Nguyen Thanh Son",
        title: "IT Student",
        dob_label: "Date of Birth: ",
        gender_label: "Gender: ",
        phone_label: "Phone: ",
        email_label: "Email: ",
        address_label: "Address: ",
        dob: "19/08/2003",
        gender: "Male",
        phone: "+84 826 624 629",
        email: "thanhsonnguyen1908@gmail.com",
        address: "62C/13, Ba Hom, Ward 13, District 6, HCM City",
        aims_title: "CAREER OBJECTIVES",
        aims_description: "As a third-year Information Technology major, I am eager to apply my knowledge and skills in a practical setting through internships and job opportunities at a tech company. My goal is to develop a career in software development, where I can contribute to innovative projects and learn from industry experts.",
        studies_title: "EDUCATION",
        studies_duration: "08/2021 _ 08/2025",
        studies_institute: "University of Science, HCM City",
        studies_status: "3rd year student",
        studies_gpa: "GPA: 3.12/4.0",
        skills_title: "SKILLS",
        skill_python: "Python",
        skill_python_level: "Basic",
        skill_c: "C/C++",
        skill_c_level: "Basic",
        skill_dotnet: ".NET/C#",
        skill_dotnet_level: "Basic",
        hobbies_title: "HOBBIES",
        hobby_music: "Listening to music, watching movies",
        hobby_games: "Playing games",
        hobby_coding: "Coding",
        hobby_research: "Researching technology",
        contact_title: "CONTACT",
        contact_website: "Personal website",
        contact_facebook: "Facebook",
        contact_email: "Email",
        contact_github: "Github"
    }
};

function changeLanguage(lang) {
    document.querySelectorAll('[data_key]').forEach(element => {
        const key = element.getAttribute('data_key');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
}
