const translations = {
    vi: {
        page_title: "Giới thiệu bản thân",
        information: "Giới thiệu",
        aims: "Mục tiêu",
        studies: "Học vấn",
        skills: "Kỹ năng",
        projects: "Dự án",
        hobbies: "Sở thích",
        contact: "Liên hệ",

        name: "Nguyễn Thanh Sơn",
        title: "Sinh viên IT",
        dob_label: "Ngày sinh: ",
        gender_label: "Giới tính: ",
        phone_label: "Điện thoại: ",
        email_label: "Email: ",
        github_label: "Github: ",
        dob: "19/08/2003",
        gender: "Nam",
        phone: "+84 826 624 629",
        email: "thanhsonnguyen1908@gmail.com",
        github: "Dolphin1908",

        aims_title: "MỤC TIÊU NGHỀ NGHIỆP",
        aims_description: "Tôi là một Nhà phát triển phần mềm đầy nhiệt huyết với nền tảng vững chắc về C# .NET, các mô hình kiến trúc hiện đại (Clean Architecture, MVVM) và công nghệ web. Tôi tận tâm trong việc xây dựng các ứng dụng hiệu quả, có khả năng mở rộng cao, đồng thời luôn khao khát vận dụng kỹ năng về thiết kế hệ thống và phát triển tính năng vào thực tế. Mục tiêu của tôi là đóng góp vào các dự án thực tế, tối ưu hóa hiệu suất hệ thống và không ngừng trau dồi năng lực kỹ thuật để đáp ứng và vượt xa các tiêu chuẩn của công ty.",
        
        studies_title: "HỌC VẤN",
        studies_duration: "08/2021 _ 08/2025",
        studies_institute: "Đại học Khoa học Tự nhiên TP.HCM",
        studies_status: "Sinh viên năm 3",
        studies_gpa: "GPA: 2.98/4.0",

        skills_title: "KỸ NĂNG",
        programming_skill: "Ngôn ngữ lập trình",
        programming_skill_description: "C#, Java, Python.",
        framework_skill: "Framework",
        framework_skill_description: "WPF.NET, Spring Boot.",
        architecture_skill: "Kiến trúc & Thiết kế",
        architecture_skill_description: "Clean Architecture, MVVM (Model-View-ViewModel), Dependency Injection.",
        database_skill: "Cơ sở dữ liệu",
        database_skill_description: "SQLite, MongoDB, MySQL.",
        tool_skill: "Công cụ",
        tool_skill_description: "Visual Studio, Git/Github, Restful APIs, Gemini APIs.",
        soft_skill: "Kỹ năng mềm",
        soft_skill_description: "Giải quyết vấn đề, làm việc nhóm, tự học, chịu áp lực.",
        skill_toeic: "TOEIC",
        skill_toeic_lr: "LR: 620.",
        skill_toeic_sw: "SW: 240.",

        projects_title: "DỰ ÁN",
        laboratory_application_project_name_1: "Laboratory Application",
        laboratory_application_project_link: "Github",
        laboratory_application_project_description_1: "Là ứng dụng học tập được phát triển bằng C#/.NET, hỗ trợ nhiều môn học. Được xây dựng dựa trên một cá nhân với mục đích học hỏi công nghệ mới.",
        project_2_name_1: "Planora",
        project_2_link: "Github",
        project_2_description_1: "Là dự án phát triển ứng dụng web quản lý tiến độ phát triển phần mềm có tích hợp AI.",
        project_2_description_2: "Trách nhiệm trong dự án:",
        project_2_description_1_item_1: "Xử lý prompt AI chuyển thành Tasks cho người dùng.",
        project_2_description_1_item_2: "Hoàn thiện chức năng chart.",
        project_3_name_1: "MessApp",
        project_3_link: "Github",
        project_3_description: "Là ứng dụng nhắn tin được phát triển bằng C#/.NET, hỗ trợ giao tiếp theo thời gian thực. Được xây dựng là một dự án cá nhân để tìm hiểu công nghệ mới.",
        project_4_name_1: "OctaTunes",
        project_4_link: "Github",
        project_4_description_1: "Là ứng dụng phát nhạc trực tuyến trên nền tảng Android tương tự Spotify. Được thiết kế và hoàn thiện với nhóm có 5 thành viên.",
        project_4_description_2: "Trách nhiệm trong dự án:",
        project_4_description_2_item_1: "Xây dựng giao diện, xử lý logic cho phân hệ Admin.",

        hobbies_title: "SỞ THÍCH",
        hobby_music: "Nghe nhạc, xem phim",
        hobby_games: "Chơi game",
        hobby_coding: "Viết code",
        hobby_research: "Nghiên cứu công nghệ",

        contact_title: "LIÊN HỆ",
        contact_website: "Website cá nhân",
        contact_email: "Email",
        contact_github: "Github"
    },
    en: {
        page_title: "Biography",
        information: "Information",
        aims: "Aims",
        studies: "Studies",
        skills: "Skills",
        projects: "Projects",
        hobbies: "Hobbies",
        contact: "Contact",

        name: "Nguyen Thanh Son",
        title: "IT Student",
        dob_label: "Date of Birth: ",
        gender_label: "Gender: ",
        phone_label: "Phone: ",
        email_label: "Email: ",
        github_label: "Github: ",
        dob: "19/08/2003",
        gender: "Male",
        phone: "+84 826 624 629",
        email: "thanhsonnguyen1908@gmail.com",
        github: "Dolphin1908",

        aims_title: "CAREER OBJECTIVES",
        aims_description: "A highly motivated Software Developer with a strong foundation in C# .NET, modern architectural patterns (Clean Architecture, MVVM), and web technologies. I am dedicated to building efficient, scalable applications and eager to leverage my skills in system design and feature development. My objective is to contribute to real-world projects, optimize system performance, and continuously hone my technical capabilities to meet and exceed company standards.",
        studies_title: "EDUCATION",
        studies_duration: "08/2021 _ 08/2025",
        studies_institute: "University of Science, HCM City",
        studies_status: "Final year student",
        studies_gpa: "GPA: 2.98/4.0",

        skills_title: "SKILLS",
        programming_skill: "Programming Languages",
        programming_skill_description: "C#, Java, Python.",
        framework_skill: "Frameworks",
        framework_skill_description: "WPF.NET, Spring Boot.",
        architecture_skill: "Architecture & Design",
        architecture_skill_description: "Clean Architecture, MVVM (Model-View-ViewModel), Dependency Injection.",
        database_skill: "Databases",
        database_skill_description: "SQLite, MongoDB, MySQL.",
        tool_skill: "Tools & Integrations",
        tool_skill_description: "Visual Studio, Git/Github, Restful APIs, Gemini APIs.",
        soft_skill: "Soft Skills",
        soft_skill_description: "Problem-solving, teamwork, self-learning, stress management.",
        skill_toeic: "TOEIC",
        skill_toeic_lr: "LR: 620.",
        skill_toeic_sw: "SW: 240.",

        projects_title: "PROJECTS",
        laboratory_application_project_name_1: "Laboratory Application",
        laboratory_application_project_link: "Github",
        laboratory_application_project_description_1: "A learning application developed with C#/.NET, supporting multiple subjects. Built as a personal project to learn new technology.",
        project_2_name_1: "Planora",
        project_2_link: "Github",
        project_2_description_1: "A web application project for managing software development progress, integrated with AI.",
        project_2_description_2: "Responsibilities in the project:",
        project_2_description_1_item_1: "Processing AI prompts into tasks for users.",
        project_2_description_1_item_2: "Completing the chart functionality.",
        project_3_name_1: "MessApp",
        project_3_link: "Github",
        project_3_description: "A messaging application developed with C#/.NET, supporting real-time communication. Built as a personal project to learn new technology.",
        project_4_name_1: "OctaTunes",
        project_4_link: "Github",
        project_4_description_1: "An online music streaming application on the Android platform, similar to Spotify. Designed and completed with a team of 5 members.",
        project_4_description_2: "Responsibilities in the project:",
        project_4_description_2_item_1: "Built the UI and handled logic for the Admin subsystem.",

        hobbies_title: "HOBBIES",
        hobby_music: "Listening to music, watching movies",
        hobby_games: "Playing games",
        hobby_coding: "Coding",
        hobby_research: "Researching technology",

        contact_title: "CONTACT",
        contact_website: "Personal website",
        contact_email: "Email",
        contact_github: "Github"
    }
};

function changeLanguage(lang) {
    document.documentElement.lang = lang;

    document.querySelectorAll('[data_key]').forEach(element => {
        const key = element.getAttribute('data_key');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
}
